# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Des points sur les virgules
email: tous@dpslv.fr
description: >
  Des formations par des développeurs pour des développeurs, certifiées
  100 % sans slide et sur mesure
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dpslv.github.io" # the base hostname & protocol for your site
twitter_username: dpslv
github_username:  dpslv
collections:
  formations:
    output: true
    permalink: /formation/:path/

# Build settings
markdown: kramdown
